# Generated by Django 4.2.7 on 2023-12-08 01:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Name')),
                ('autoload_method', models.CharField(choices=[('empty_method', '----------'), ('cbrf_method', 'CBRF rate loader'), ('ecb_method', 'ECB rate loader'), ('binance_method', 'Binance rate loader'), ('garantex_method', 'Garantex rate loader')], default='empty_method', max_length=100, verbose_name='Autoload method')),
                ('base_currency', models.CharField(blank=True, max_length=10, null=True, verbose_name='Base currency')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('interval_value', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Autoload interval value')),
                ('tickers', models.TextField(blank=True, default='', verbose_name='Tickers')),
                ('autoload_lastrun', models.DateTimeField(blank=True, null=True, verbose_name='Autoload last run')),
                ('autoload_lastresult', models.JSONField(default=dict, verbose_name='Autoload last result')),
            ],
            options={
                'verbose_name': 'Currency rate type',
                'verbose_name_plural': 'Currency rate types',
            },
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_from', models.CharField(max_length=10)),
                ('currency_to', models.CharField(max_length=10)),
                ('rate', models.DecimalField(decimal_places=10, max_digits=20)),
                ('rate_date', models.DateTimeField(auto_now_add=True)),
                ('nominal', models.IntegerField()),
                ('rate_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='currency_rates', to='currency_test.currencyratetype', verbose_name='Rate type')),
            ],
        ),
    ]
